spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # ???? JPQL? ??? ??; QueryDSL??? ??? JPQL? ????? ??? ? ??
  data:
    web:
      pageable:
        max-page-size: 1000
        default-page-size: 10

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace

server:
  port: 8083
